# Generated by Django 2.0.7 on 2018-11-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.FloatField()),
                ('time', models.TimeField()),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('ascent', models.FloatField(default=0.0)),
                ('descent', models.FloatField(default=0.0)),
                ('max_speed', models.FloatField(default=0.0)),
                ('cadence', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='bikes.Bike')),
            ],
        ),
    ]
