# Generated by Django 2.1.4 on 2018-12-06 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181203_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 6)),
        ),
    ]
