# Generated by Django 2.1.4 on 2018-12-13 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20181206_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 13)),
        ),
    ]
