# Generated by Django 2.1.4 on 2018-12-18 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20181213_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 18)),
        ),
    ]
