# Generated by Django 2.1.4 on 2019-01-08 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20181218_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 8)),
        ),
    ]
