# Generated by Django 2.1.4 on 2019-01-24 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190121_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_set', to='bikes.Bike'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 24)),
        ),
    ]
