# Generated by Django 2.1.4 on 2019-01-28 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190124_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='checked',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 28)),
        ),
    ]
