# Generated by Django 2.1.4 on 2019-01-29 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190128_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
