# Generated by Django 2.1.4 on 2019-01-29 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='distance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(20000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='year',
            field=models.IntegerField(default=1970, validators=[django.core.validators.MaxLengthValidator(2050), django.core.validators.MinLengthValidator(2000)]),
            preserve_default=False,
        ),
    ]
