# Generated by Django 2.1.4 on 2019-01-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20190129_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
    ]
