# Generated by Django 2.1.4 on 2019-01-29 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20190129_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(2050), django.core.validators.MinLengthValidator(2000)]),
        ),
    ]
