# Generated by Django 2.1.4 on 2019-01-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20190129_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='distance',
            new_name='goal',
        ),
    ]
