# Generated by Django 3.0.2 on 2020-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endomondo_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='endomondo_password',
            field=models.CharField(max_length=254, verbose_name='Endomondo password'),
        ),
    ]
