# Generated by Django 2.1.4 on 2019-01-08 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(99), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='componentstatistic',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.Bike'),
        ),
        migrations.AlterField(
            model_name='componentstatistic',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bikes.Component'),
        ),
    ]
