# Generated by Django 2.1.4 on 2019-01-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20190108_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentstatistic',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='componentstatistic',
            name='brand',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
