# Generated by Django 3.0.6 on 2021-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20191231_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
