# Generated by Django 3.0.6 on 2021-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
