# Generated by Django 5.0.7 on 2024-08-02 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0005_bike_retired"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComponentStatistic",
            new_name="ComponentWear",
        ),
    ]
